source 'http://rubygems.org'

gem 'rails', '3.0.1'

# Bundle edge Rails instead:
#gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby','1.2.5', :require => 'sqlite3'
gem 'gravatar_image_tag', '1.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri', '1.4.1'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development,
group :test do
  gem 'rspec',    '2.8.0'
  gem 'annotate', '2.4.0'
  gem "autotest"
  gem "autotest-rails"
  gem 'factory_girl', '2.6.0'
end

